import { defineAppForm, type AppForm } from "./define";

export const onboardingForm = defineAppForm({
  title: "Onboarding",
  slug: "onboarding",
  status: "active",
  description:
    "Stepped wizard. Next validates the current page; submit uses the snapshot.",
  meta: {
    submitLabel: "Finish onboarding",
    steps: {
      "1": "About you",
      "2": "Work",
      "3": "Setup",
      "4": "Confirm",
    },
  },
  fields: [
    {
      id: "fullName",
      type: "text",
      required: true,
      label: "Full name",
      minLength: 2,
      maxLength: 80,
      meta: { step: 1, placeholder: "Ada Lovelace", width: "half" },
    },
    {
      id: "email",
      type: "email",
      required: true,
      label: "Work email",
      meta: { step: 1, width: "half" },
    },
    {
      id: "city",
      type: "text",
      label: "City",
      meta: { step: 1, placeholder: "Optional" },
    },
    {
      id: "role",
      type: "select",
      required: true,
      label: "Role",
      defaultValue: "eng",
      meta: { step: 2, widget: "radio" },
      options: [
        {
          value: "eng",
          label: "Engineer",
          meta: { description: "Builds the product" },
        },
        { value: "pm", label: "Product" },
        { value: "ops", label: "Operations" },
      ],
    },
    {
      id: "team",
      type: "text",
      label: "Team",
      description: "Shown when role is Engineer",
      showWhen: { field: "role", equals: "eng" },
      meta: { step: 2, placeholder: "Platform" },
    },
    {
      id: "startDate",
      type: "date",
      required: true,
      label: "Start date",
      meta: { step: 3 },
    },
    {
      id: "tracks",
      type: "multiSelect",
      label: "What do you want to set up first?",
      meta: { step: 3, widget: "chips" },
      options: [
        { value: "api", label: "API" },
        { value: "ui", label: "UI" },
        { value: "db", label: "Database" },
      ],
    },
    {
      id: "apiNote",
      type: "text",
      label: "Which API surface?",
      showWhen: { field: "tracks", includes: "api" },
      meta: { step: 3 },
    },
    {
      id: "hours",
      type: "number",
      label: "Hours this week",
      min: 0,
      max: 40,
      integer: true,
      meta: { step: 3, suffix: "h", help: "Whole hours only" },
    },
    {
      id: "ok",
      type: "boolean",
      required: true,
      label: "I can be contacted about this setup",
      unsetOnOff: true,
      meta: { step: 4, widget: "switch" },
    },
    {
      id: "notes",
      type: "text",
      label: "Anything we should know?",
      maxLength: 280,
      meta: { step: 4, multiline: true },
    },
  ],
} satisfies AppForm);
